# Generated by Django 6.0.3 on 2026-03-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_managers_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('TRAVELER', 'Пътуващ'), ('OPERATOR', 'Оператор'), ('ADMIN', 'Администратор')], default='TRAVELER', help_text='Определя правата на потребителя', max_length=20, verbose_name='Роля'),
        ),
    ]
