# Generated by Django 6.0.3 on 2026-04-02 22:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='Профилна снимка'),
            preserve_default=False,
        ),
    ]
