# Generated by Django 6.0.3 on 2026-03-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Име на спирка')),
                ('stop_id', models.CharField(help_text='Официален идентификатор на спирката', max_length=10, unique=True, verbose_name='Номер на спирка')),
                ('neighborhood', models.CharField(blank=True, max_length=50, null=True, verbose_name='Квартал')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес/Ориентир')),
                ('is_active', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Географска ширина на спирката', max_digits=9, null=True, verbose_name='Ширина (latitude)')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Географска дължина на спирката', max_digits=9, null=True, verbose_name='Дължина (longitude)')),
            ],
            options={
                'verbose_name': 'Спирка',
                'verbose_name_plural': 'Спирки',
                'ordering': ['stop_id', 'name'],
            },
        ),
    ]
