# Generated by Django 6.0.3 on 2026-03-29 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Подаден от')),
                ('category', models.CharField(choices=[('delay', 'Закъснение'), ('skipped', 'Пропуснат курс'), ('station', 'Проблем със спирка'), ('behavior', 'Грубо отношение'), ('repair', 'Повреда/Ремонт'), ('other', 'Друго')], default='other', max_length=20, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание на проблема')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата на създаване')),
                ('status', models.CharField(choices=[('new', 'Нов'), ('in_progress', 'В процес на обработка'), ('resolved', 'Решен'), ('rejected', 'Отхвърлен')], default='new', max_length=20, verbose_name='Статус')),
                ('bus_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='transport.busline', verbose_name='Линия')),
                ('stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='stations.station', verbose_name='Спирка')),
            ],
            options={
                'verbose_name': 'Сигнал',
                'verbose_name_plural': 'Сигнали',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='reports_rep_status_c732ef_idx'), models.Index(fields=['created_at'], name='reports_rep_created_a6aabf_idx')],
            },
        ),
    ]
