# Generated by Django 6.0.3 on 2026-03-29 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Име на план')),
                ('duration_months', models.PositiveIntegerField(verbose_name='Продължителност (месеци)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Номер на карта')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Валидна до')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to=settings.AUTH_USER_MODEL, verbose_name='Потребител')),
            ],
        ),
        migrations.CreateModel(
            name='CardSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.card')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Абонамент на карта',
                'verbose_name_plural': 'Абонаменти на карти',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.AddField(
            model_name='card',
            name='plans',
            field=models.ManyToManyField(related_name='cards', through='subscriptions.CardSubscription', to='subscriptions.subscriptionplan', verbose_name='Абонаменти'),
        ),
    ]
