# Generated by Django 6.0.3 on 2026-03-26 15:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Номер на линия')),
                ('route_bus', models.CharField(max_length=100, verbose_name='Име на маршрут')),
                ('description', models.TextField(blank=True, help_text='Кратка информация за линията', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Линия',
                'verbose_name_plural': 'Линии',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Позиция на спирката в маршрута (започва от 1)', validators=[django.core.validators.MinValueValidator(1, message='Поредният номер трябва да бъде поне 1.')], verbose_name='Пореден номер в маршрута')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='transport.busline', verbose_name='Линия')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='stations.station', verbose_name='Спирка')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршрути',
                'ordering': ['line', 'position'],
            },
        ),
        migrations.AddField(
            model_name='busline',
            name='stops',
            field=models.ManyToManyField(related_name='bus_lines', through='transport.Route', to='stations.station', verbose_name='Спирки'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='route_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('line', 'stop'), name='unique_stop_per_line'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('line', 'position'), name='unique_position_per_line'),
        ),
    ]
