# Generated by Django 6.0.3 on 2026-04-01 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField(verbose_name='Време на пристигане')),
                ('day_type', models.CharField(choices=[('weekday', 'Делник'), ('weekend', 'Празник/Уикенд')], default='weekday', max_length=10)),
                ('direction', models.CharField(choices=[('forward', 'Отиване'), ('backward', 'Връщане')], default='forward', max_length=10, verbose_name='Посока')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='transport.busline')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='stations.station')),
            ],
            options={
                'verbose_name': 'Разписание',
                'verbose_name_plural': 'Разписания',
                'ordering': ['arrival_time'],
                'constraints': [models.UniqueConstraint(fields=('line', 'stop', 'direction', 'arrival_time', 'day_type'), name='unique_schedule_entry')],
            },
        ),
    ]
